### ISSUE TITLE
not-small max-width instead of min-width?

### ISSUE THREAD

**Issue by lukebrooker** [mrmrs/tachyons-type-scale#1]
Was just trying to use this module and was wondering is the following line supposed to be `@custom-media --breakpoint-not-small screen and (min-width: 48em);` not max-width?

https://github.com/mrmrs/tachyons-type-scale/blob/master/src/tachyons-type-scale.css#L1

**Comment by mrmrs** [comment]
You are correct - sorry about that. Will fix ASAP.

**Comment by mrmrs** [comment]
Seems to be a problem in a number of modules - thanks for catching this. Should be updated on npm shortly.

**Comment by mrmrs** [comment]
@lukebrooker This has been fixed if you install the latest version. Thanks again for pointing this out.

**Comment by lukebrooker** [comment]
That was quick :smiley: Glad I could “help”.

**Comment by mrmrs** [comment]
Bug reporting is an extremely important part of open source stuff. Highly appreciated.
